import { type InventoryStatus } from "@/lib/ocr-inventory-data";
import { type WorkflowRecord } from "@/lib/workflow-state";

export type ExtractedField = {
  label: string;
  value: string;
  confidence: number;
};

export type BillOfLadingSample = {
  id: string;
  fileName: string;
  documentUrl: string;
  documentIsPdf?: boolean;
  title: string;
  uploadedBy: string;
  productName: string;
  sku: string;
  quantity: number;
  inventoryValue: string;
  confidence: number;
  fields: ExtractedField[];
};

export const billingProjectSamples: BillOfLadingSample[] = [
  {
    id: "DS-BILL-20001",
    fileName: "billing-1-maersk-bol.png",
    documentUrl: "/bills-2/billing 1.png",
    title: "Ocean Bill of Lading",
    uploadedBy: "FTP",
    productName: "Steel cables - Maersk ocean freight",
    sku: "BOL-MAEU-245804210",
    quantity: 26,
    inventoryValue: "17,487.000 KGS",
    confidence: 97,
    fields: [
      { label: "Bill of Lading No.", value: "MAEU245804210", confidence: 99 },
      { label: "Document Type", value: "Ocean Bill of Lading", confidence: 99 },
      { label: "Carrier", value: "Maersk Line", confidence: 99 },
      { label: "SCAC", value: "MAEU", confidence: 99 },
      { label: "Booking No.", value: "245804210", confidence: 99 },
      { label: "Export Reference", value: "NEX227083", confidence: 98 },
      { label: "Service Contract", value: "340034892", confidence: 98 },
      {
        label: "Shipper",
        value: "NEXANS, 4 ALLEE DE L'ARCHE, 92400 COURBEVOIE, FRANCE",
        confidence: 97,
      },
      {
        label: "Consignee",
        value:
          "THE SIAM CEMENT PUBLIC COMPANY LIMITED, 1 SIAM CEMENT ROAD, BANGSUE, BANGKOK 10800, THAILAND",
        confidence: 96,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      { label: "Onward Inland Routing", value: "MERCHANT HAULIER", confidence: 97 },
      { label: "Vessel / Voyage", value: "MAERSK CAMDEN / 438W", confidence: 98 },
      { label: "Place of Receipt", value: "LE HAVRE, FRANCE", confidence: 98 },
      { label: "Port of Loading", value: "Le Havre, France", confidence: 98 },
      { label: "Port of Discharge", value: "Laem Chabang, Thailand", confidence: 98 },
      { label: "Place of Delivery", value: "LAEM CHABANG, THAILAND", confidence: 98 },
      { label: "Container No.", value: "MSKU6997444", confidence: 98 },
      { label: "Seal No.", value: "22654248", confidence: 97 },
      { label: "Container / Package Count", value: "1 x 20 GP / 26 packages", confidence: 97 },
      {
        label: "Description of Goods",
        value:
          "STEEL CABLES; HS CODE 73121090; SHIPPER'S LOAD, STOW AND COUNT; 1 CONTAINER SAID TO CONTAIN 26 PACKAGES",
        confidence: 96,
      },
      { label: "Gross Weight", value: "17,487.000 KGS", confidence: 98 },
      { label: "Measurement", value: "24.700 CBM", confidence: 98 },
      { label: "Freight Terms", value: "OCEAN FREIGHT - PREPAID", confidence: 98 },
      { label: "Place / Date of Issue", value: "LE HAVRE, FRANCE / 25 MAY 2024", confidence: 98 },
      {
        label: "Signed for Carrier",
        value: "Agustina Squillet, as Agent(s) for the Carrier Maersk A/S",
        confidence: 94,
      },
      { label: "Document Status", value: "Original - Negotiable", confidence: 96 },
    ],
  },
  {
    id: "DS-BILL-20002",
    fileName: "billing-3-msc-hol.png",
    documentUrl: "/bills-2/billing 5.png",
    title: "House Bill of Lading",
    uploadedBy: "SFTP",
    productName: "Plastic household articles - MSC shipment",
    sku: "HOL-MEDUNB240412345",
    quantity: 2,
    inventoryValue: "17,600.000 KGS",
    confidence: 94,
    fields: [
      { label: "Bill of Lading No.", value: "MEDUNB240412345", confidence: 98 },
      { label: "Document Type", value: "House Bill of Lading", confidence: 96 },
      { label: "Carrier", value: "Mediterranean Shipping Company S.A.", confidence: 98 },
      { label: "Booking No.", value: "UNB240412345", confidence: 98 },
      { label: "Export Reference", value: "YGK2403001", confidence: 97 },
      {
        label: "Shipper",
        value:
          "ZHEJIANG YONGKANG IMP. & EXP. CO., LTD., NO. 2099 HUANGCHENG ROAD, YONGKANG, ZHEJIANG 321300, CHINA",
        confidence: 94,
      },
      {
        label: "Consignee",
        value: "TRIMEX INTERNATIONAL TRADING LLC, P.O. BOX 8541, DUBAI, UNITED ARAB EMIRATES",
        confidence: 95,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      { label: "Vessel / Voyage", value: "MSC LORETO / 426B", confidence: 96 },
      { label: "Port of Loading", value: "Ningbo, China", confidence: 98 },
      { label: "Port of Discharge", value: "Jebel Ali, United Arab Emirates", confidence: 97 },
      { label: "Place of Delivery", value: "JEBEL ALI, UNITED ARAB EMIRATES", confidence: 97 },
      { label: "Container / Seal 1", value: "MSCU7712340 / CN5669224", confidence: 94 },
      { label: "Container / Seal 2", value: "MSCU7712356 / CN566925", confidence: 92 },
      { label: "Container Count", value: "2 x 20' DRY CONTAINER", confidence: 96 },
      {
        label: "Description of Goods",
        value: "PLASTIC HOUSEHOLD ARTICLES; HS CODE 3924.90; COUNTRY OF ORIGIN: CHINA",
        confidence: 94,
      },
      { label: "Gross Weight", value: "17,600.000 KGS", confidence: 98 },
      { label: "Measurement", value: "53.000 CBM", confidence: 97 },
      { label: "Freight Terms", value: "FREIGHT PREPAID", confidence: 97 },
      { label: "Place / Date of Issue", value: "NINGBO / 12 APR 2024", confidence: 98 },
      { label: "Laden on Board", value: "12 APR 2024, NINGBO", confidence: 97 },
      {
        label: "Signed for Carrier",
        value: "MSC Mediterranean Shipping Company S.A. / As Agent",
        confidence: 94,
      },
    ],
  },
  {
    id: "DS-BILL-20003",
    fileName: "billing-4-cosco-bol.png",
    documentUrl: "/bills-2/billing 4.png",
    title: "Ocean Bill of Lading",
    uploadedBy: "FTP",
    productName: "Men's jackets - COSCO ocean shipment",
    sku: "BOL-COSU6405123450",
    quantity: 590,
    inventoryValue: "18,900.000 KGS",
    confidence: 96,
    fields: [
      { label: "Bill of Lading No.", value: "COSU6405123450", confidence: 99 },
      { label: "Document Type", value: "Ocean Bill of Lading", confidence: 98 },
      { label: "Carrier", value: "COSCO Shipping", confidence: 99 },
      { label: "Booking No.", value: "6405123450", confidence: 99 },
      { label: "Export Reference", value: "HNMC2403012", confidence: 97 },
      {
        label: "Shipper",
        value:
          "QINGDAO HAINIU MACHINERY CO., LTD., NO. 55 TAIYUAN ROAD, QINGDAO, SHANDONG 266071, CHINA",
        confidence: 95,
      },
      {
        label: "Consignee",
        value:
          "AMERICAN EAGLE OUTFITTERS INC., 77 HOT METAL STREET, PITTSBURGH, PA 15203, UNITED STATES",
        confidence: 97,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      { label: "Vessel / Voyage", value: "COSCO SHIPPING AQUARIUS / 088E", confidence: 96 },
      { label: "Port of Loading", value: "Qingdao, China", confidence: 98 },
      { label: "Port of Discharge", value: "Los Angeles, CA, United States", confidence: 98 },
      { label: "Place of Delivery", value: "LOS ANGELES, CA, UNITED STATES", confidence: 98 },
      { label: "Container / Seal", value: "MSMU912545 / 789456", confidence: 94 },
      { label: "Container Type", value: "1 x 40' HIGH CUBE", confidence: 97 },
      { label: "Packages", value: "590 cartons", confidence: 98 },
      {
        label: "Description of Goods",
        value: "MEN'S JACKETS; 100% POLYESTER; HS CODE 6201.93; COUNTRY OF ORIGIN: CHINA",
        confidence: 95,
      },
      { label: "Gross Weight", value: "18,900.000 KGS", confidence: 98 },
      { label: "Measurement", value: "68.200 CBM", confidence: 98 },
      { label: "Freight Terms", value: "FREIGHT PREPAID", confidence: 98 },
      { label: "Place / Date of Issue", value: "QINGDAO / 05 APR 2024", confidence: 98 },
      { label: "Laden on Board", value: "05 APR 2024, QINGDAO", confidence: 97 },
      { label: "Signed for Carrier", value: "COSCO Shipping Lines Co., Ltd.", confidence: 95 },
    ],
  },
  {
    id: "DS-BILL-20004",
    fileName: "billing-5-one-hol.png",
    documentUrl: "/bills-2/billing 5.png",
    title: "House Bill of Lading",
    uploadedBy: "SFTP",
    productName: "Home appliances - ONE shipment",
    sku: "HOL-ONEYTNB240389123",
    quantity: 4,
    inventoryValue: "45,120.000 KGS",
    confidence: 93,
    fields: [
      { label: "Bill of Lading No.", value: "ONEYTNB240389123", confidence: 98 },
      { label: "Document Type", value: "House Bill of Lading", confidence: 96 },
      { label: "Carrier", value: "Ocean Network Express", confidence: 98 },
      { label: "Booking No.", value: "YTNB240309123", confidence: 98 },
      { label: "Export Reference", value: "YS2402008", confidence: 97 },
      {
        label: "Shipper",
        value:
          "CIXI CITY YOUNG SUN ELECTRIC APPLIANCE CO., LTD., NO. 188 ZHONGSHAN EAST ROAD, CIXI, ZHEJIANG 315300, CHINA",
        confidence: 93,
      },
      {
        label: "Consignee",
        value: "WALMART INC., 2001 SE 10TH STREET, BENTONVILLE, AR 72716, UNITED STATES",
        confidence: 97,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      { label: "Vessel / Voyage", value: "ONE APUS / 046W", confidence: 96 },
      { label: "Port of Loading", value: "Yantian, China", confidence: 98 },
      { label: "Port of Discharge", value: "Savannah, GA, United States", confidence: 98 },
      { label: "Place of Delivery", value: "SAVANNAH, GA, UNITED STATES", confidence: 98 },
      {
        label: "Container / Seal Numbers",
        value: "TCCU2008761 / 112233; 112234; 112235; 112236; TCCU27691237",
        confidence: 91,
      },
      { label: "Container Count", value: "4 x 20' DRY CONTAINER", confidence: 97 },
      {
        label: "Description of Goods",
        value: "HOME APPLIANCES; HS CODE 8509.80; COUNTRY OF ORIGIN: CHINA",
        confidence: 95,
      },
      { label: "Gross Weight", value: "45,120.000 KGS", confidence: 98 },
      { label: "Measurement", value: "120.880 CBM", confidence: 98 },
      { label: "Freight Terms", value: "FREIGHT PREPAID", confidence: 98 },
      { label: "Place / Date of Issue", value: "YANTIAN / 28 MAR 2024", confidence: 98 },
      { label: "Laden on Board", value: "28 MAR 2024, YANTIAN", confidence: 97 },
      { label: "Signed for Carrier", value: "Ocean Network Express (China) Ltd.", confidence: 94 },
    ],
  },
  {
    id: "DS-BILL-20005",
    fileName: "billing-6-linbis-bol.png",
    documentUrl: "/bills-2/billing 6.png",
    title: "Ocean Bill of Lading",
    uploadedBy: "FTP",
    productName: "Cotton T-shirts - Linbis ocean freight",
    sku: "BOL-HLCUSHA240524098",
    quantity: 500,
    inventoryValue: "$2,850.00",
    confidence: 98,
    fields: [
      { label: "Bill of Lading No.", value: "HLCUSHA240524098", confidence: 99 },
      { label: "Document Type", value: "Ocean Bill of Lading - Non-Negotiable", confidence: 99 },
      { label: "Carrier", value: "Linbis Logistics Software", confidence: 98 },
      { label: "Booking No.", value: "BK20240524098", confidence: 99 },
      { label: "B/L Date", value: "24-MAY-2024", confidence: 99 },
      {
        label: "Export References",
        value: "PO No: PO4500123456; Invoice No: INV/24-25/0156",
        confidence: 98,
      },
      { label: "OTI No.", value: "OTI#7812345", confidence: 98 },
      {
        label: "Shipper",
        value:
          "ABC TEXTILES PVT. LTD., 301, WeWork, Oberoi Commerz II, Goregaon East, Mumbai - 400063, Maharashtra, INDIA; Tel: +91 22 6720 0500",
        confidence: 98,
      },
      {
        label: "Consignee",
        value:
          "GLOBAL IMPORTS LLC, 540 WEST 26TH STREET, SUITE 401, NEW YORK, NY 10001, UNITED STATES OF AMERICA; Tel: +1 212 947 8500",
        confidence: 98,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      {
        label: "Forwarding Agent",
        value:
          "FREIGHTEX FORWARDERS PVT. LTD., 1002, B Wing, 10th Floor, Marathon Innova, Lower Parel, Mumbai - 400013, India; Tel: +91 22 4920 5400",
        confidence: 97,
      },
      { label: "Point of Origin", value: "Maharashtra, INDIA", confidence: 98 },
      {
        label: "Domestic Routing / Export Instruction",
        value: "FREIGHT PREPAID; SUBJECT TO MSC TARIFF & CONDITIONS; NO DEVIATION ALLOWED",
        confidence: 97,
      },
      { label: "Pre-Carriage By", value: "TRUCK", confidence: 99 },
      { label: "Place of Receipt", value: "MUMBAI, INDIA", confidence: 99 },
      { label: "Vessel / Voyage", value: "MSC CAPELLA / 245W", confidence: 98 },
      { label: "Port of Loading", value: "Nhava Sheva (INNSA)", confidence: 99 },
      { label: "Port of Discharge", value: "New York (USNYC)", confidence: 99 },
      { label: "Place of Delivery", value: "NEWARK, NJ, USA", confidence: 99 },
      { label: "Loading Pier / Terminal", value: "JNPCT", confidence: 99 },
      { label: "Type of Move", value: "CY / CY - CONTAINER", confidence: 98 },
      { label: "Containerized", value: "Yes", confidence: 99 },
      {
        label: "Marks and Numbers",
        value: "ABC TEXTILES PVT. LTD.; STYLE NO.: TSH-1001; P.O. NO.: PO4500123456; MADE IN INDIA",
        confidence: 97,
      },
      { label: "Packages", value: "500 cartons", confidence: 99 },
      {
        label: "Description of Goods",
        value:
          "500 CARTONS OF COTTON T-SHIRTS; 100% COTTON, MEN'S; HS CODE: 6109.10; PACKING: 1 POLY BAG PER PIECE; 50 PIECES PER CARTON; CARTON NO. 1 TO 500",
        confidence: 98,
      },
      { label: "Gross Weight", value: "8,450.000 KGS", confidence: 99 },
      { label: "Measurement", value: "42.500 CBM / 1,500.260 CBFT", confidence: 99 },
      { label: "Declared Value", value: "100,000.00 USD", confidence: 98 },
      { label: "Freight Charges", value: "OCEAN FREIGHT - 2,850.00 USD PREPAID", confidence: 99 },
      { label: "Grand Total", value: "2,850.00 USD", confidence: 99 },
      { label: "Place of Signing", value: "MUMBAI, INDIA", confidence: 98 },
      { label: "Authorized Signatory", value: "Rakesh Sharma", confidence: 97 },
    ],
  },
  {
    id: "DS-BILL-20006",
    fileName: "billing-7-hapag-lloyd-hol.png",
    documentUrl: "/bills-2/billing 7.png",
    title: "House Bill of Lading",
    uploadedBy: "SFTP",
    productName: "Solar modules - Hapag-Lloyd shipment",
    sku: "HOL-HLXU624123456",
    quantity: 18,
    inventoryValue: "7,920.000 KGS",
    confidence: 95,
    fields: [
      { label: "Bill of Lading No.", value: "HLXU624123456", confidence: 99 },
      { label: "Document Type", value: "House Bill of Lading", confidence: 96 },
      { label: "Carrier", value: "Hapag-Lloyd", confidence: 99 },
      { label: "Booking No.", value: "624123456", confidence: 99 },
      {
        label: "Export References",
        value: "IEC NO. 0518003445; GSTIN: 06AABCG2605K1Z4",
        confidence: 96,
      },
      {
        label: "Shipper",
        value:
          "GOLDI SOLAR PRIVATE LIMITED, PLOT NO. 73, SECTOR-3, IMT MANESAR, GURUGRAM, HARYANA - 122050, INDIA",
        confidence: 96,
      },
      {
        label: "Consignee",
        value:
          "GREEN ENERGY SOLUTIONS FZCO, P.O. BOX 61234, JEBEL ALI FREE ZONE, DUBAI, UNITED ARAB EMIRATES; TEL: +971 4 886 5366",
        confidence: 97,
      },
      { label: "Notify Party", value: "SAME AS CONSIGNEE", confidence: 99 },
      {
        label: "Forwarding Agent",
        value:
          "DHL GLOBAL FORWARDING (INDIA) PVT. LTD., C-301, GANESH MERIDIAN, OPP. KARGIL PETROL PUMP, S.G. HIGHWAY, AHMEDABAD - 380000, INDIA",
        confidence: 97,
      },
      { label: "Place of Receipt", value: "JEBEL ALI, UNITED ARAB EMIRATES", confidence: 97 },
      { label: "Vessel / Voyage", value: "YM ELIXIR / 052W", confidence: 97 },
      { label: "Port of Loading", value: "Mundra, India", confidence: 99 },
      { label: "Port of Discharge", value: "Jebel Ali, United Arab Emirates", confidence: 99 },
      { label: "Place of Delivery", value: "JEBEL ALI, UNITED ARAB EMIRATES", confidence: 99 },
      {
        label: "Marks and Numbers",
        value: "GSLPL/MUNDRA; C/NO. 1-18; MADE IN INDIA",
        confidence: 97,
      },
      { label: "Packages", value: "18 cartons", confidence: 99 },
      {
        label: "Description of Goods",
        value: "SOLAR MODULES; HS CODE: 8541.40; FREIGHT PREPAID",
        confidence: 97,
      },
      { label: "Gross Weight", value: "7,920.000 KGS", confidence: 99 },
      { label: "Measurement", value: "66.240 CBM", confidence: 99 },
      { label: "Freight Terms", value: "OCEAN FREIGHT - PREPAID", confidence: 99 },
      { label: "Place / Date of Issue", value: "MUNDRA, INDIA / 27 MAY 2024", confidence: 98 },
      {
        label: "Signed for Carrier",
        value: "HAPAG-LLOYD (INDIA) PVT. LTD., as Agent for the Carrier Hapag-Lloyd AG",
        confidence: 96,
      },
    ],
  },
];

export const uploadedBolSamples: BillOfLadingSample[] = [
  {
    id: "DS-TRAINITY-832611300031",
    fileName: "BOL_832611300031.pdf",
    documentUrl: "/bills-2/BOL_832611300031.pdf",
    documentIsPdf: true,
    title: "Bill of Lading",
    uploadedBy: "Manual Upload",
    productName: "Heat exchanger shipment - Goodway Technologies to HEXONIC",
    sku: "BOL-832611300031",
    quantity: 1,
    inventoryValue: "450 LBS",
    confidence: 98,
    fields: [
      { label: "Date", value: "04/23/2026", confidence: 99 },
      { label: "BOL", value: "832611300031", confidence: 99 },
      { label: "SCAC Code", value: "", confidence: 85 },
      { label: "Customer PO", value: "", confidence: 85 },
      { label: "PRO/Manifest ID", value: "416378082", confidence: 99 },
      { label: "Quote #", value: "10000343535133", confidence: 99 },
      { label: "Carrier Name", value: "XPO Logistics", confidence: 99 },
      { label: "Carrier Address", value: "", confidence: 85 },
      { label: "Carrier State", value: "", confidence: 85 },
      { label: "Carrier City", value: "", confidence: 85 },
      { label: "Carrier Zip Code", value: "", confidence: 85 },
      { label: "Carrier Phone #", value: "(800) 755-2728", confidence: 99 },
      { label: "Origin / Shipper Name", value: "Goodway Technologies", confidence: 99 },
      { label: "Origin / Shipper Address", value: "420 West Avenue", confidence: 99 },
      { label: "Origin / Shipper City", value: "Stamford", confidence: 99 },
      { label: "Origin / Shipper State", value: "CT", confidence: 99 },
      { label: "Origin / Shipper Zip Code", value: "690", confidence: 97 },
      { label: "Origin / Shipper Contact", value: "Shino Santiago", confidence: 98 },
      { label: "Origin / Shipper Phone", value: "203 359 4708 6354", confidence: 97 },
      { label: "Origin / Shipper Email(s)", value: "Itlops@trinitylogistics.com", confidence: 96 },
      { label: "Destination / Consignee Name", value: "HEXONIC", confidence: 99 },
      { label: "Destination / Consignee Address", value: "178 Hyatt Street", confidence: 99 },
      { label: "Destination / Consignee City", value: "Gaffney", confidence: 99 },
      { label: "Destination / Consignee State", value: "SC", confidence: 99 },
      { label: "Destination / Consignee Zip Code", value: "29341", confidence: 99 },
      { label: "Destination / Consignee Contact", value: "Pawel Markowsk", confidence: 97 },
      { label: "Destination / Consignee Phone", value: "864-384-5570", confidence: 98 },
      { label: "Destination / Consignee Email(s)", value: "pmarkowski@hexonic.com", confidence: 99 },
      { label: "Freight Charges Terms", value: "ThirdParty, Prepaid", confidence: 99 },
      { label: "Bill To Name", value: "Trinity Logistics, Inc.", confidence: 99 },
      { label: "Bill To Address", value: "PO Box 1486", confidence: 99 },
      { label: "Bill To City", value: "DE", confidence: 96 },
      { label: "Bill To State", value: "Seaford", confidence: 96 },
      { label: "Bill To Zip Code", value: "19973", confidence: 99 },
      { label: "Bill To Phone", value: "800-846-3400", confidence: 99 },
      { label: "Bill To Email(s)", value: "ltlops@trinitylogistics.com", confidence: 99 },
      { label: "QTY/PCS", value: "1 Pallets", confidence: 99 },
      { label: "Weight", value: "450", confidence: 99 },
      { label: "Class", value: "70", confidence: 99 },
      { label: "NMFC #", value: "122830-04", confidence: 99 },
      { label: "SKU", value: "", confidence: 85 },
      { label: "HZ", value: "", confidence: 85 },
      { label: "Description", value: "Heat Exchanger (12 or higher)", confidence: 99 },
      { label: "Dimensions", value: "32x22x27", confidence: 99 },
      { label: "Total Weight", value: "450", confidence: 99 },
      { label: "Special Instructions", value: "", confidence: 85 },
      { label: "Pickup Notes", value: "", confidence: 85 },
      { label: "Delivery Notes", value: "Call Pawel once at the gate to enter. 8038692875,", confidence: 98 },
    ],
  },
  {
    id: "DS-TRAINITY-832525100049",
    fileName: "BOL_832525100049.pdf",
    documentUrl: "/bills-2/BOL_832525100049.pdf",
    documentIsPdf: true,
    title: "Bill of Lading",
    uploadedBy: "Manual Upload",
    productName: "Heat exchanger shipment - HEXONIC to Lonza Biologics",
    sku: "BOL-832525100049",
    quantity: 2,
    inventoryValue: "492 LBS",
    confidence: 98,
    fields: [
      { label: "Date", value: "09/09/2025", confidence: 99 },
      { label: "BOL", value: "832525100049", confidence: 99 },
      { label: "SCAC Code", value: "", confidence: 85 },
      { label: "Customer PO", value: "SO-778", confidence: 99 },
      { label: "PRO/Manifest ID", value: "800055255", confidence: 99 },
      { label: "Quote #", value: "10000229290431", confidence: 99 },
      { label: "Carrier Name", value: "XPO Logistics", confidence: 99 },
      { label: "Carrier Address", value: "", confidence: 85 },
      { label: "Carrier State", value: "", confidence: 85 },
      { label: "Carrier City", value: "", confidence: 85 },
      { label: "Carrier Zip Code", value: "", confidence: 85 },
      { label: "Carrier Phone #", value: "734-994-6600", confidence: 99 },
      { label: "Origin / Shipper Name", value: "HEXONIC", confidence: 99 },
      { label: "Origin / Shipper Address", value: "178 Hyatt Street", confidence: 99 },
      { label: "Origin / Shipper City", value: "Gaffney", confidence: 99 },
      { label: "Origin / Shipper State", value: "SC", confidence: 99 },
      { label: "Origin / Shipper Zip Code", value: "29341", confidence: 99 },
      { label: "Origin / Shipper Contact", value: "Pawel Markowsk", confidence: 97 },
      { label: "Origin / Shipper Phone", value: "8038692875", confidence: 99 },
      { label: "Origin / Shipper Email(s)", value: "pmarkowski@hexonic.com", confidence: 99 },
      { label: "Destination / Consignee Name", value: "Lonza Biologics", confidence: 99 },
      { label: "Destination / Consignee Address", value: "40 Goose Bay Drive", confidence: 99 },
      { label: "Destination / Consignee City", value: "Portsmouth", confidence: 99 },
      { label: "Destination / Consignee State", value: "NH", confidence: 99 },
      { label: "Destination / Consignee Zip Code", value: "3801", confidence: 99 },
      { label: "Destination / Consignee Contact", value: "Jason", confidence: 98 },
      { label: "Destination / Consignee Phone", value: "6039288367", confidence: 99 },
      { label: "Destination / Consignee Email(s)", value: "ltlops@trinitylogistics.com", confidence: 99 },
      { label: "Freight Charges Terms", value: "ThirdParty, Prepaid", confidence: 99 },
      { label: "Bill To Name", value: "Trinity Logistics, Inc.", confidence: 99 },
      { label: "Bill To Address", value: "PO Box 1486", confidence: 99 },
      { label: "Bill To City", value: "DE", confidence: 96 },
      { label: "Bill To State", value: "Seaford", confidence: 96 },
      { label: "Bill To Zip Code", value: "19973", confidence: 99 },
      { label: "Bill To Phone", value: "800-846-3400", confidence: 99 },
      { label: "Bill To Email(s)", value: "ltlops@trinitylogistics.com", confidence: 99 },
      { label: "QTY/PCS", value: "2 Pallets", confidence: 99 },
      { label: "Weight", value: "492", confidence: 99 },
      { label: "Class", value: "77.5", confidence: 99 },
      { label: "NMFC #", value: "122830-04", confidence: 99 },
      { label: "SKU", value: "", confidence: 85 },
      { label: "HZ", value: "", confidence: 85 },
      { label: "Description", value: "Heat Exchanger (12 or higher)", confidence: 99 },
      { label: "Dimensions", value: "92x18x19", confidence: 99 },
      { label: "Total Weight", value: "492", confidence: 99 },
      { label: "Special Instructions", value: "", confidence: 85 },
      { label: "Pickup Notes", value: "Call Pawel once at the gate to enter. 8038692875,", confidence: 98 },
      { label: "Delivery Notes", value: "Appointment Required,", confidence: 98 },
    ],
  },
];

export const billOfLadingSamples: BillOfLadingSample[] = [
  {
    id: "DS-BOL-70006",
    fileName: "OID000011-Ocean-Bill-Of-Lading-Non-Negotiable-Rated.png",
    documentUrl: "/bills/OID000011-Ocean-Bill-Of-Lading-Non-Negotiable-Rated.png",
    title: "Ocean Bill of Lading - Non Negotiable Rated",
    uploadedBy: "Ocean SFTP Drop",
    productName: "Ocean freight shipment documentation",
    sku: "BOL-OCEAN-0011",
    quantity: 1,
    inventoryValue: "$4,860.00",
    confidence: 94,
    fields: [
      { label: "Bill of Lading No.", value: "OID000011", confidence: 97 },
      { label: "Document Type", value: "Ocean Bill of Lading - Non Negotiable", confidence: 96 },
      { label: "Shipper", value: "Blue Harbor Exporters Ltd.", confidence: 92 },
      { label: "Consignee", value: "Atlantic Retail Imports LLC", confidence: 91 },
      { label: "Vessel / Voyage", value: "MV Pacific Trader / PT421E", confidence: 89 },
      { label: "Port of Loading", value: "Shanghai, China", confidence: 94 },
      { label: "Port of Discharge", value: "Los Angeles, USA", confidence: 94 },
      { label: "Container No.", value: "MSCU 458921-7", confidence: 93 },
      { label: "Seal No.", value: "SL893420", confidence: 90 },
      { label: "Freight Terms", value: "Prepaid", confidence: 92 },
      { label: "Packages", value: "420 cartons", confidence: 91 },
      { label: "Gross Weight", value: "8,640 KG", confidence: 90 },
    ],
  },
  {
    id: "DS-BOL-70005",
    fileName: "house-bill-of-lading-content-3.png",
    documentUrl: "/bills/house-bill-of-lading-content-3.png",
    title: "House Bill of Lading",
    uploadedBy: "Forwarder Portal",
    productName: "House B/L shipment packet",
    sku: "HBL-FWD-3003",
    quantity: 1,
    inventoryValue: "$2,940.00",
    confidence: 91,
    fields: [
      { label: "Bill of Lading No.", value: "HBL-2026-3003", confidence: 94 },
      { label: "Document Type", value: "House Bill of Lading", confidence: 95 },
      { label: "Shipper", value: "Global Textile Mills", confidence: 90 },
      { label: "Consignee", value: "Northstar Apparel Group", confidence: 88 },
      { label: "Notify Party", value: "Northstar Customs Desk", confidence: 87 },
      { label: "Vessel / Voyage", value: "Ever Globe / EG118W", confidence: 88 },
      { label: "Port of Loading", value: "Nhava Sheva, India", confidence: 91 },
      { label: "Port of Discharge", value: "New York, USA", confidence: 90 },
      { label: "Container No.", value: "TEMU 772184-0", confidence: 89 },
      { label: "Seal No.", value: "IN449821", confidence: 87 },
      { label: "Packages", value: "188 bales", confidence: 91 },
      { label: "Gross Weight", value: "12,480 KG", confidence: 88 },
    ],
  },
  {
    id: "DS-BOL-70004",
    fileName: "sample-bill-of-lading-usa-freight-forwarder.png",
    documentUrl: "/bills/sample-bill-of-lading-usa-freight-forwarder.png",
    title: "USA Freight Forwarder Bill of Lading",
    uploadedBy: "Freight Email Inbox",
    productName: "Freight forwarder B/L sample",
    sku: "BOL-USA-4412",
    quantity: 1,
    inventoryValue: "$1,725.00",
    confidence: 88,
    fields: [
      { label: "Bill of Lading No.", value: "FF-44120-US", confidence: 92 },
      { label: "Document Type", value: "Freight Forwarder Bill of Lading", confidence: 90 },
      { label: "Shipper", value: "Midwest Machinery Parts", confidence: 87 },
      { label: "Consignee", value: "Harborline Distribution", confidence: 86 },
      { label: "Carrier", value: "USA Freight Forwarder", confidence: 89 },
      { label: "Port of Loading", value: "Savannah, USA", confidence: 88 },
      { label: "Port of Discharge", value: "Rotterdam, Netherlands", confidence: 87 },
      { label: "Container No.", value: "CMAU 339871-2", confidence: 85 },
      { label: "Seal No.", value: "US771024", confidence: 84 },
      { label: "Freight Terms", value: "Collect", confidence: 88 },
      { label: "Packages", value: "62 crates", confidence: 86 },
      { label: "Gross Weight", value: "9,210 KG", confidence: 85 },
    ],
  },
  {
    id: "DS-BOL-70003",
    fileName: "bearer-bill-of-lading.jpg",
    documentUrl: "/bills/bearer-bill-of-lading.jpg",
    title: "Bearer Bill of Lading",
    uploadedBy: "Carrier Scan Upload",
    productName: "Bearer B/L scan",
    sku: "BOL-BEARER-5904",
    quantity: 1,
    inventoryValue: "$3,180.00",
    confidence: 86,
    fields: [
      { label: "Bill of Lading No.", value: "BBL-5904-26", confidence: 90 },
      { label: "Document Type", value: "Bearer Bill of Lading", confidence: 91 },
      { label: "Shipper", value: "Eastern Metals Export Co.", confidence: 84 },
      { label: "Consignee", value: "To Bearer / Order", confidence: 83 },
      { label: "Vessel / Voyage", value: "MSC Horizon / MH604A", confidence: 85 },
      { label: "Port of Loading", value: "Singapore", confidence: 88 },
      { label: "Port of Discharge", value: "Hamburg, Germany", confidence: 87 },
      { label: "Container No.", value: "MSKU 904512-8", confidence: 84 },
      { label: "Seal No.", value: "SG118903", confidence: 82 },
      { label: "Packages", value: "34 pallets", confidence: 86 },
      { label: "Gross Weight", value: "18,900 KG", confidence: 85 },
      { label: "Freight Terms", value: "Prepaid", confidence: 86 },
    ],
  },
  {
    id: "DS-BOL-70002",
    fileName: "Ocean Bill of Lading 400x518px.jpg",
    documentUrl: "/bills/Ocean Bill of Lading 400x518px.jpg",
    title: "Ocean Bill of Lading",
    uploadedBy: "Ocean Carrier Portal",
    productName: "Ocean B/L scanned form",
    sku: "BOL-OCEAN-4005",
    quantity: 1,
    inventoryValue: "$2,250.00",
    confidence: 84,
    fields: [
      { label: "Bill of Lading No.", value: "OBL-4005-18", confidence: 88 },
      { label: "Document Type", value: "Ocean Bill of Lading", confidence: 90 },
      { label: "Shipper", value: "Pacific Home Goods", confidence: 83 },
      { label: "Consignee", value: "Metro Retail Logistics", confidence: 82 },
      { label: "Vessel / Voyage", value: "Ocean Mariner / OM227", confidence: 82 },
      { label: "Port of Loading", value: "Busan, Korea", confidence: 87 },
      { label: "Port of Discharge", value: "Seattle, USA", confidence: 86 },
      { label: "Container No.", value: "OOLU 118402-5", confidence: 81 },
      { label: "Seal No.", value: "KR552081", confidence: 80 },
      { label: "Packages", value: "510 cartons", confidence: 84 },
      { label: "Gross Weight", value: "6,780 KG", confidence: 83 },
      { label: "Freight Terms", value: "Prepaid", confidence: 85 },
    ],
  },
  {
    id: "DS-BOL-70001",
    fileName: "bill-of-lading.pdf",
    documentUrl: "/bills/bill-of-lading.pdf",
    documentIsPdf: true,
    title: "Bill of Lading PDF",
    uploadedBy: "Document Intake PDF",
    productName: "PDF Bill of Lading",
    sku: "BOL-PDF-1001",
    quantity: 1,
    inventoryValue: "$3,520.00",
    confidence: 89,
    fields: [
      { label: "Bill of Lading No.", value: "BOL-PDF-1001", confidence: 93 },
      { label: "Document Type", value: "Bill of Lading PDF", confidence: 92 },
      { label: "Shipper", value: "Continental Export House", confidence: 88 },
      { label: "Consignee", value: "Summit Import Services", confidence: 88 },
      { label: "Notify Party", value: "Summit Import Brokerage", confidence: 86 },
      { label: "Vessel / Voyage", value: "Maersk Denver / MD309", confidence: 87 },
      { label: "Port of Loading", value: "Colombo, Sri Lanka", confidence: 89 },
      { label: "Port of Discharge", value: "Long Beach, USA", confidence: 90 },
      { label: "Container No.", value: "MRKU 581044-3", confidence: 87 },
      { label: "Seal No.", value: "LK219004", confidence: 85 },
      { label: "Packages", value: "96 packages", confidence: 88 },
      { label: "Gross Weight", value: "14,240 KG", confidence: 87 },
    ],
  },
];

export const worstCaseBillOfLadingSamples: BillOfLadingSample[] = [
  {
    id: "DS-BOL-OCR-90002",
    fileName: "worst-case-ocean-bill-of-lading.png",
    documentUrl: "/bills/OID000011-Ocean-Bill-Of-Lading-Non-Negotiable-Rated.png",
    title: "Ocean Bill of Lading - Worst OCR Case",
    uploadedBy: "Damaged Ocean Scan",
    productName: "Low confidence ocean B/L review",
    sku: "BOL-OCEAN-REVIEW",
    quantity: 1,
    inventoryValue: "Pending Review",
    confidence: 43,
    fields: [
      { label: "Bill of Lading No.", value: "OID00?011", confidence: 48 },
      {
        label: "Document Type",
        value: "Ocean Bill of Lading - possible non negotiable",
        confidence: 52,
      },
      { label: "Shipper", value: "Blue Harbor Exporters L?d.", confidence: 44 },
      { label: "Consignee", value: "Atlantic Retail Imp?rts LLC", confidence: 41 },
      { label: "Vessel / Voyage", value: "MV Pacific T?ader / PT42?E", confidence: 38 },
      { label: "Port of Loading", value: "Shang?ai, China", confidence: 46 },
      { label: "Port of Discharge", value: "Los Ang?les, USA", confidence: 45 },
      { label: "Container No.", value: "MSCU 45?921-?", confidence: 34 },
      { label: "Seal No.", value: "SL?93420", confidence: 32 },
      { label: "Freight Terms", value: "Prepa?d", confidence: 47 },
      { label: "Packages", value: "42? cartons", confidence: 39 },
      { label: "Gross Weight", value: "8,?40 KG", confidence: 36 },
    ],
  },
  {
    id: "DS-BOL-OCR-90001",
    fileName: "worst-case-house-bill-of-lading.png",
    documentUrl: "/bills/house-bill-of-lading-content-3.png",
    title: "House Bill of Lading - Worst OCR Case",
    uploadedBy: "Blurred Forwarder Upload",
    productName: "Low confidence house B/L review",
    sku: "HBL-REVIEW-LOW",
    quantity: 1,
    inventoryValue: "Pending Review",
    confidence: 47,
    fields: [
      { label: "Bill of Lading No.", value: "HBL-2026-3?03", confidence: 51 },
      { label: "Document Type", value: "House Bill of Lading", confidence: 62 },
      { label: "Shipper", value: "Global Textile M?lls", confidence: 44 },
      { label: "Consignee", value: "Northstar Apparel Gr?up", confidence: 42 },
      { label: "Notify Party", value: "Northstar Customs D?sk", confidence: 38 },
      { label: "Vessel / Voyage", value: "Ever Gl?be / EG11?W", confidence: 40 },
      { label: "Port of Loading", value: "Nhava She?a, India", confidence: 49 },
      { label: "Port of Discharge", value: "New Y?rk, USA", confidence: 48 },
      { label: "Container No.", value: "TEMU 77?184-0", confidence: 35 },
      { label: "Seal No.", value: "IN44?821", confidence: 34 },
      { label: "Packages", value: "18? bales", confidence: 43 },
      { label: "Gross Weight", value: "12,?80 KG", confidence: 37 },
    ],
  },
];

export function makeBillOfLadingRecord(
  sample: BillOfLadingSample,
  status: InventoryStatus,
  owner: string,
  uploadDate: string,
): WorkflowRecord {
  return {
    id: sample.id,
    fileName: sample.fileName,
    uploadDate,
    uploadedBy: sample.uploadedBy,
    status,
    owner,
    productName: sample.productName,
    sku: sample.sku,
    quantity: sample.quantity,
    inventoryValue: sample.inventoryValue,
    confidence: sample.confidence,
    exceptionReason: "",
    documentType: sample.title.includes("House") ? "HBL" : "BOL",
    documentUrl: sample.documentUrl,
    documentIsPdf: sample.documentIsPdf,
    ocrFields: sample.fields,
  };
}

export function isBillOfLadingRecord(record: Pick<WorkflowRecord, "documentType">) {
  return (
    record.documentType === "BOL" ||
    record.documentType === "HBL" ||
    record.documentType === "HOL" ||
    record.documentType.includes("Bill of Lading")
  );
}


