/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkflowQueueRouteImport } from './routes/_app/workflow-queue'
import { Route as AppWorkflowBuilderRouteImport } from './routes/_app/workflow-builder'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppQcReviewRouteImport } from './routes/_app/qc-review'
import { Route as AppProcessingQueueRouteImport } from './routes/_app/processing-queue'
import { Route as AppOcrReviewQueueRouteImport } from './routes/_app/ocr-review-queue'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppManualReviewRouteImport } from './routes/_app/manual-review'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppExportRouteImport } from './routes/_app/export'
import { Route as AppExceptionsRouteImport } from './routes/_app/exceptions'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAiValidationRouteImport } from './routes/_app/ai-validation'
import { Route as AppOcrIndexRouteImport } from './routes/_app/ocr/index'
import { Route as AppOcrReviewRouteImport } from './routes/_app/ocr/review'
import { Route as AppFunctionsWorkflowRoutingApprovalRouteImport } from './routes/_app/functions/workflow-routing-approval'
import { Route as AppFunctionsValidationHumanReviewRouteImport } from './routes/_app/functions/validation-human-review'
import { Route as AppFunctionsTemplateManagementRouteImport } from './routes/_app/functions/template-management'
import { Route as AppFunctionsOcrExtractionDataStructuringRouteImport } from './routes/_app/functions/ocr-extraction-data-structuring'
import { Route as AppFunctionsIntegrationReportingAuditRouteImport } from './routes/_app/functions/integration-reporting-audit'
import { Route as AppFunctionsDocumentIntakeRouteImport } from './routes/_app/functions/document-intake'
import { Route as AppFunctionsDocumentClassificationFilteringRouteImport } from './routes/_app/functions/document-classification-filtering'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowQueueRoute = AppWorkflowQueueRouteImport.update({
  id: '/workflow-queue',
  path: '/workflow-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowBuilderRoute = AppWorkflowBuilderRouteImport.update({
  id: '/workflow-builder',
  path: '/workflow-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQcReviewRoute = AppQcReviewRouteImport.update({
  id: '/qc-review',
  path: '/qc-review',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingQueueRoute = AppProcessingQueueRouteImport.update({
  id: '/processing-queue',
  path: '/processing-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrReviewQueueRoute = AppOcrReviewQueueRouteImport.update({
  id: '/ocr-review-queue',
  path: '/ocr-review-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppManualReviewRoute = AppManualReviewRouteImport.update({
  id: '/manual-review',
  path: '/manual-review',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsRoute = AppExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAiValidationRoute = AppAiValidationRouteImport.update({
  id: '/ai-validation',
  path: '/ai-validation',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrIndexRoute = AppOcrIndexRouteImport.update({
  id: '/ocr/',
  path: '/ocr/',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrReviewRoute = AppOcrReviewRouteImport.update({
  id: '/ocr/review',
  path: '/ocr/review',
  getParentRoute: () => AppRoute,
} as any)
const AppFunctionsWorkflowRoutingApprovalRoute =
  AppFunctionsWorkflowRoutingApprovalRouteImport.update({
    id: '/functions/workflow-routing-approval',
    path: '/functions/workflow-routing-approval',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsValidationHumanReviewRoute =
  AppFunctionsValidationHumanReviewRouteImport.update({
    id: '/functions/validation-human-review',
    path: '/functions/validation-human-review',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsTemplateManagementRoute =
  AppFunctionsTemplateManagementRouteImport.update({
    id: '/functions/template-management',
    path: '/functions/template-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsOcrExtractionDataStructuringRoute =
  AppFunctionsOcrExtractionDataStructuringRouteImport.update({
    id: '/functions/ocr-extraction-data-structuring',
    path: '/functions/ocr-extraction-data-structuring',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsIntegrationReportingAuditRoute =
  AppFunctionsIntegrationReportingAuditRouteImport.update({
    id: '/functions/integration-reporting-audit',
    path: '/functions/integration-reporting-audit',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsDocumentIntakeRoute =
  AppFunctionsDocumentIntakeRouteImport.update({
    id: '/functions/document-intake',
    path: '/functions/document-intake',
    getParentRoute: () => AppRoute,
  } as any)
const AppFunctionsDocumentClassificationFilteringRoute =
  AppFunctionsDocumentClassificationFilteringRouteImport.update({
    id: '/functions/document-classification-filtering',
    path: '/functions/document-classification-filtering',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/ai-validation': typeof AppAiValidationRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/exceptions': typeof AppExceptionsRoute
  '/export': typeof AppExportRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/manual-review': typeof AppManualReviewRoute
  '/monitoring': typeof AppMonitoringRoute
  '/notifications': typeof AppNotificationsRoute
  '/ocr-review-queue': typeof AppOcrReviewQueueRoute
  '/processing-queue': typeof AppProcessingQueueRoute
  '/qc-review': typeof AppQcReviewRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/workflow-builder': typeof AppWorkflowBuilderRoute
  '/workflow-queue': typeof AppWorkflowQueueRoute
  '/functions/document-classification-filtering': typeof AppFunctionsDocumentClassificationFilteringRoute
  '/functions/document-intake': typeof AppFunctionsDocumentIntakeRoute
  '/functions/integration-reporting-audit': typeof AppFunctionsIntegrationReportingAuditRoute
  '/functions/ocr-extraction-data-structuring': typeof AppFunctionsOcrExtractionDataStructuringRoute
  '/functions/template-management': typeof AppFunctionsTemplateManagementRoute
  '/functions/validation-human-review': typeof AppFunctionsValidationHumanReviewRoute
  '/functions/workflow-routing-approval': typeof AppFunctionsWorkflowRoutingApprovalRoute
  '/ocr/review': typeof AppOcrReviewRoute
  '/ocr/': typeof AppOcrIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/ai-validation': typeof AppAiValidationRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/exceptions': typeof AppExceptionsRoute
  '/export': typeof AppExportRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/manual-review': typeof AppManualReviewRoute
  '/monitoring': typeof AppMonitoringRoute
  '/notifications': typeof AppNotificationsRoute
  '/ocr-review-queue': typeof AppOcrReviewQueueRoute
  '/processing-queue': typeof AppProcessingQueueRoute
  '/qc-review': typeof AppQcReviewRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/workflow-builder': typeof AppWorkflowBuilderRoute
  '/workflow-queue': typeof AppWorkflowQueueRoute
  '/': typeof AppIndexRoute
  '/functions/document-classification-filtering': typeof AppFunctionsDocumentClassificationFilteringRoute
  '/functions/document-intake': typeof AppFunctionsDocumentIntakeRoute
  '/functions/integration-reporting-audit': typeof AppFunctionsIntegrationReportingAuditRoute
  '/functions/ocr-extraction-data-structuring': typeof AppFunctionsOcrExtractionDataStructuringRoute
  '/functions/template-management': typeof AppFunctionsTemplateManagementRoute
  '/functions/validation-human-review': typeof AppFunctionsValidationHumanReviewRoute
  '/functions/workflow-routing-approval': typeof AppFunctionsWorkflowRoutingApprovalRoute
  '/ocr/review': typeof AppOcrReviewRoute
  '/ocr': typeof AppOcrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/_app/ai-validation': typeof AppAiValidationRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/exceptions': typeof AppExceptionsRoute
  '/_app/export': typeof AppExportRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/manual-review': typeof AppManualReviewRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/ocr-review-queue': typeof AppOcrReviewQueueRoute
  '/_app/processing-queue': typeof AppProcessingQueueRoute
  '/_app/qc-review': typeof AppQcReviewRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workflow-builder': typeof AppWorkflowBuilderRoute
  '/_app/workflow-queue': typeof AppWorkflowQueueRoute
  '/_app/': typeof AppIndexRoute
  '/_app/functions/document-classification-filtering': typeof AppFunctionsDocumentClassificationFilteringRoute
  '/_app/functions/document-intake': typeof AppFunctionsDocumentIntakeRoute
  '/_app/functions/integration-reporting-audit': typeof AppFunctionsIntegrationReportingAuditRoute
  '/_app/functions/ocr-extraction-data-structuring': typeof AppFunctionsOcrExtractionDataStructuringRoute
  '/_app/functions/template-management': typeof AppFunctionsTemplateManagementRoute
  '/_app/functions/validation-human-review': typeof AppFunctionsValidationHumanReviewRoute
  '/_app/functions/workflow-routing-approval': typeof AppFunctionsWorkflowRoutingApprovalRoute
  '/_app/ocr/review': typeof AppOcrReviewRoute
  '/_app/ocr/': typeof AppOcrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspace'
    | '/ai-validation'
    | '/approvals'
    | '/audit-logs'
    | '/exceptions'
    | '/export'
    | '/integrations'
    | '/inventory'
    | '/manual-review'
    | '/monitoring'
    | '/notifications'
    | '/ocr-review-queue'
    | '/processing-queue'
    | '/qc-review'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/workflow-builder'
    | '/workflow-queue'
    | '/functions/document-classification-filtering'
    | '/functions/document-intake'
    | '/functions/integration-reporting-audit'
    | '/functions/ocr-extraction-data-structuring'
    | '/functions/template-management'
    | '/functions/validation-human-review'
    | '/functions/workflow-routing-approval'
    | '/ocr/review'
    | '/ocr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/workspace'
    | '/ai-validation'
    | '/approvals'
    | '/audit-logs'
    | '/exceptions'
    | '/export'
    | '/integrations'
    | '/inventory'
    | '/manual-review'
    | '/monitoring'
    | '/notifications'
    | '/ocr-review-queue'
    | '/processing-queue'
    | '/qc-review'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/workflow-builder'
    | '/workflow-queue'
    | '/'
    | '/functions/document-classification-filtering'
    | '/functions/document-intake'
    | '/functions/integration-reporting-audit'
    | '/functions/ocr-extraction-data-structuring'
    | '/functions/template-management'
    | '/functions/validation-human-review'
    | '/functions/workflow-routing-approval'
    | '/ocr/review'
    | '/ocr'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/workspace'
    | '/_app/ai-validation'
    | '/_app/approvals'
    | '/_app/audit-logs'
    | '/_app/exceptions'
    | '/_app/export'
    | '/_app/integrations'
    | '/_app/inventory'
    | '/_app/manual-review'
    | '/_app/monitoring'
    | '/_app/notifications'
    | '/_app/ocr-review-queue'
    | '/_app/processing-queue'
    | '/_app/qc-review'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/workflow-builder'
    | '/_app/workflow-queue'
    | '/_app/'
    | '/_app/functions/document-classification-filtering'
    | '/_app/functions/document-intake'
    | '/_app/functions/integration-reporting-audit'
    | '/_app/functions/ocr-extraction-data-structuring'
    | '/_app/functions/template-management'
    | '/_app/functions/validation-human-review'
    | '/_app/functions/workflow-routing-approval'
    | '/_app/ocr/review'
    | '/_app/ocr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflow-queue': {
      id: '/_app/workflow-queue'
      path: '/workflow-queue'
      fullPath: '/workflow-queue'
      preLoaderRoute: typeof AppWorkflowQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflow-builder': {
      id: '/_app/workflow-builder'
      path: '/workflow-builder'
      fullPath: '/workflow-builder'
      preLoaderRoute: typeof AppWorkflowBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qc-review': {
      id: '/_app/qc-review'
      path: '/qc-review'
      fullPath: '/qc-review'
      preLoaderRoute: typeof AppQcReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processing-queue': {
      id: '/_app/processing-queue'
      path: '/processing-queue'
      fullPath: '/processing-queue'
      preLoaderRoute: typeof AppProcessingQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ocr-review-queue': {
      id: '/_app/ocr-review-queue'
      path: '/ocr-review-queue'
      fullPath: '/ocr-review-queue'
      preLoaderRoute: typeof AppOcrReviewQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual-review': {
      id: '/_app/manual-review'
      path: '/manual-review'
      fullPath: '/manual-review'
      preLoaderRoute: typeof AppManualReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exceptions': {
      id: '/_app/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof AppExceptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-validation': {
      id: '/_app/ai-validation'
      path: '/ai-validation'
      fullPath: '/ai-validation'
      preLoaderRoute: typeof AppAiValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ocr/': {
      id: '/_app/ocr/'
      path: '/ocr'
      fullPath: '/ocr/'
      preLoaderRoute: typeof AppOcrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ocr/review': {
      id: '/_app/ocr/review'
      path: '/ocr/review'
      fullPath: '/ocr/review'
      preLoaderRoute: typeof AppOcrReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/workflow-routing-approval': {
      id: '/_app/functions/workflow-routing-approval'
      path: '/functions/workflow-routing-approval'
      fullPath: '/functions/workflow-routing-approval'
      preLoaderRoute: typeof AppFunctionsWorkflowRoutingApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/validation-human-review': {
      id: '/_app/functions/validation-human-review'
      path: '/functions/validation-human-review'
      fullPath: '/functions/validation-human-review'
      preLoaderRoute: typeof AppFunctionsValidationHumanReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/template-management': {
      id: '/_app/functions/template-management'
      path: '/functions/template-management'
      fullPath: '/functions/template-management'
      preLoaderRoute: typeof AppFunctionsTemplateManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/ocr-extraction-data-structuring': {
      id: '/_app/functions/ocr-extraction-data-structuring'
      path: '/functions/ocr-extraction-data-structuring'
      fullPath: '/functions/ocr-extraction-data-structuring'
      preLoaderRoute: typeof AppFunctionsOcrExtractionDataStructuringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/integration-reporting-audit': {
      id: '/_app/functions/integration-reporting-audit'
      path: '/functions/integration-reporting-audit'
      fullPath: '/functions/integration-reporting-audit'
      preLoaderRoute: typeof AppFunctionsIntegrationReportingAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/document-intake': {
      id: '/_app/functions/document-intake'
      path: '/functions/document-intake'
      fullPath: '/functions/document-intake'
      preLoaderRoute: typeof AppFunctionsDocumentIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions/document-classification-filtering': {
      id: '/_app/functions/document-classification-filtering'
      path: '/functions/document-classification-filtering'
      fullPath: '/functions/document-classification-filtering'
      preLoaderRoute: typeof AppFunctionsDocumentClassificationFilteringRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiValidationRoute: typeof AppAiValidationRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppExceptionsRoute: typeof AppExceptionsRoute
  AppExportRoute: typeof AppExportRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppManualReviewRoute: typeof AppManualReviewRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOcrReviewQueueRoute: typeof AppOcrReviewQueueRoute
  AppProcessingQueueRoute: typeof AppProcessingQueueRoute
  AppQcReviewRoute: typeof AppQcReviewRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkflowBuilderRoute: typeof AppWorkflowBuilderRoute
  AppWorkflowQueueRoute: typeof AppWorkflowQueueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFunctionsDocumentClassificationFilteringRoute: typeof AppFunctionsDocumentClassificationFilteringRoute
  AppFunctionsDocumentIntakeRoute: typeof AppFunctionsDocumentIntakeRoute
  AppFunctionsIntegrationReportingAuditRoute: typeof AppFunctionsIntegrationReportingAuditRoute
  AppFunctionsOcrExtractionDataStructuringRoute: typeof AppFunctionsOcrExtractionDataStructuringRoute
  AppFunctionsTemplateManagementRoute: typeof AppFunctionsTemplateManagementRoute
  AppFunctionsValidationHumanReviewRoute: typeof AppFunctionsValidationHumanReviewRoute
  AppFunctionsWorkflowRoutingApprovalRoute: typeof AppFunctionsWorkflowRoutingApprovalRoute
  AppOcrReviewRoute: typeof AppOcrReviewRoute
  AppOcrIndexRoute: typeof AppOcrIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiValidationRoute: AppAiValidationRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppExceptionsRoute: AppExceptionsRoute,
  AppExportRoute: AppExportRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppManualReviewRoute: AppManualReviewRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOcrReviewQueueRoute: AppOcrReviewQueueRoute,
  AppProcessingQueueRoute: AppProcessingQueueRoute,
  AppQcReviewRoute: AppQcReviewRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkflowBuilderRoute: AppWorkflowBuilderRoute,
  AppWorkflowQueueRoute: AppWorkflowQueueRoute,
  AppIndexRoute: AppIndexRoute,
  AppFunctionsDocumentClassificationFilteringRoute:
    AppFunctionsDocumentClassificationFilteringRoute,
  AppFunctionsDocumentIntakeRoute: AppFunctionsDocumentIntakeRoute,
  AppFunctionsIntegrationReportingAuditRoute:
    AppFunctionsIntegrationReportingAuditRoute,
  AppFunctionsOcrExtractionDataStructuringRoute:
    AppFunctionsOcrExtractionDataStructuringRoute,
  AppFunctionsTemplateManagementRoute: AppFunctionsTemplateManagementRoute,
  AppFunctionsValidationHumanReviewRoute:
    AppFunctionsValidationHumanReviewRoute,
  AppFunctionsWorkflowRoutingApprovalRoute:
    AppFunctionsWorkflowRoutingApprovalRoute,
  AppOcrReviewRoute: AppOcrReviewRoute,
  AppOcrIndexRoute: AppOcrIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
